In [10]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [14]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [20]:
import numpy as np
a=np.zeros((3,3))
print (a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [26]:
import numpy as np
a=np.full((3,3),9)
print (a)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [52]:
print(s.dtype)

float64


In [21]:
import numpy as np
a=np.random.random((3,3))
print (a)

[[0.67456821 0.07946272 0.76667949]
 [0.60258368 0.0341389  0.05763529]
 [0.35021516 0.97153222 0.7209817 ]]


In [8]:
import numpy as np
a=np.arange(5,101,5)
print (a)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [22]:
import numpy as np
b=a.reshape((3,3))
print (b)

[[0.67456821 0.07946272 0.76667949]
 [0.60258368 0.0341389  0.05763529]
 [0.35021516 0.97153222 0.7209817 ]]


In [23]:
import numpy as np
b=a.reshape((3,3))
print(b)

[[0.67456821 0.07946272 0.76667949]
 [0.60258368 0.0341389  0.05763529]
 [0.35021516 0.97153222 0.7209817 ]]


In [24]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [41]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [42]:
b=a.reshape((3,4))
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
b=a.flatten()
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [46]:
print(b.size)

12


In [48]:
s=np.full((3,2),'w')
print(s)

[['w' 'w']
 ['w' 'w']
 ['w' 'w']]


In [29]:
s=np.full((3,2),10)
print(s)

[[10 10]
 [10 10]
 [10 10]]


In [57]:
import numpy as np
a=np.full((3,3),9)
print (a)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [58]:
print(a.dtype)

int32


In [62]:
print(a.astype("f"))

[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


In [67]:
f=a.astype("i")
print(f)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [49]:
import numpy as np
b=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [39]:
print(a[0:3:2])

[[1 2 3]
 [7 8 9]]


In [44]:
print(a[3::])

[[10 11 12]]


In [72]:
print(a[3::])

[[10 11 12]]


In [73]:
print(a[1::])

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [53]:
print(a[0:2])

[ 4 12]


In [47]:
a=np.arange(5,50,5)
print (a)

[ 5 10 15 20 25 30 35 40 45]


In [46]:
import numpy as np
a=np.arange(5,50,5)
print (a)

[ 5 10 15 20 25 30 35 40 45]


In [3]:
import numpy as np
b=np.arange(5,50,5)
print (b)

[ 5 10 15 20 25 30 35 40 45]


In [4]:
import numpy as np
a=np.arange(5,50,5)
print (a)

[ 5 10 15 20 25 30 35 40 45]


In [48]:
import numpy as np
b=np.arange(5,50,5)
print (b)

[ 5 10 15 20 25 30 35 40 45]


In [1]:
import numpy as np
a=np.arange(5,50,5)
print (a)


[ 5 10 15 20 25 30 35 40 45]


In [7]:
import numpy as sm
a=sm.array([[5,6,4,1],[3,8,5,2],[7,4,8,3],[2,1,0,4]])
print(a)

[[5 6 4 1]
 [3 8 5 2]
 [7 4 8 3]
 [2 1 0 4]]


In [8]:
b=a[:2,:3]
print(b)

[[5 6 4]
 [3 8 5]]


In [9]:
b=a[:2,:4]
print(b)

[[5 6 4 1]
 [3 8 5 2]]


In [10]:
b=a[[0,1,2,3],[3,2,1,0]]
print(b)

[1 5 4 2]


In [11]:
cond=a>5
print(a[cond])

[6 8 7 8]


In [13]:
cond=a>6
print(a[cond])

[8 7 8]


In [14]:
print(a[::2])

[[5 6 4 1]
 [7 4 8 3]]


In [23]:
e=sm.array([1,5,7])
f=sm.array([2,4,6])
v=sm.concatenate((e,f))
print(v)

[1 5 7 2 4 6]


In [24]:
e=sm.array([1,5,7])
f=sm.array([2,4,6])
v=sm.hstack((e,f))
print(v)


[1 5 7 2 4 6]


In [25]:
e=sm.array([1,5,7])
f=sm.array([2,4,6])
v=sm.vstack((e,f))
print(v)


[[1 5 7]
 [2 4 6]]


In [26]:
e=sm.array([1,5,7])
f=sm.array([2,4,6])
v=sm.dstack((e,f))
print(v)

[[[1 2]
  [5 4]
  [7 6]]]


In [40]:
a=sm.array([4,2,8,3,9,5,1,7])
b=sm.array_split(a,4)
print(a)
print(b)
print(b[0])
print(b[1])
print(b[2])
print(b[3])

[4 2 8 3 9 5 1 7]
[array([4, 2]), array([8, 3]), array([9, 5]), array([1, 7])]
[4 2]
[8 3]
[9 5]
[1 7]


In [39]:
a=sm.array([4,2,8,3,9,5,1,7])
b=sm.array_split(a,3)
print(b[0])
print(b[1])
print(b[2])


[4 2 8]
[3 9 5]
[1 7]


In [7]:
import numpy as sm
a=sm.array([2,3,5,3,9,4,3,3,3])
x=sm.where(a==3)
print(x)

(array([1, 3, 6, 7, 8], dtype=int64),)


In [10]:
a=sm.array([2,3,5,9,4,6,10])
x=sm.where(a%2==0)
print(x)

(array([0, 5, 6, 8], dtype=int64),)


In [23]:
a=sm.array([1,2,3,4,5,6,7,8,9])
x=sm.searchsorted(a,4,side='left')
print(x)

3


In [24]:
x=sm.searchsorted(a,4,side='right')
print(x)

4


In [25]:
a=sm.array([6,3,9,2,0,4,6])
y=sm.sort(a)
print(y)

[0 2 3 4 6 6 9]


In [27]:
 a=sm.array([[6,3,9],[2,0,4]])
y=sm.sort(a)
print(y)

[[3 6 9]
 [0 2 4]]


In [29]:
a=sm.array([6,4,7,2])
x=[True,False,True,True]
y=a[x]
print(y)

[6 7 2]


In [32]:
a=sm.array([6,4,7,2])
x=a>4
y=a[x]
print(y)

[6 7]


In [33]:
x=a>=4
y=a[x]
print(y)

[6 4 7]


In [34]:
x=a>=2
y=a[x]
print(y)

[6 4 7 2]


In [40]:
a=sm.array([4,8,12,16,20])
b=sm.array([6,12,18,24,30])
print(a+b)

[10 20 30 40 50]


In [39]:
print(a-b)

[ 2  4  6  8 10]


In [41]:
print(a*b)

[ 24  96 216 384 600]


In [42]:
print(a/b)

[0.66666667 0.66666667 0.66666667 0.66666667 0.66666667]


In [43]:
print(a.dot(b))

1320


In [44]:
c=4
y=(c*a)
print(y)

[16 32 48 64 80]


In [52]:
def function(x,y):
    if x>y:
        return x-y
    else:
        return x+y
a=sm.array([4,12,12,16,30])
b=sm.array([6,8,18,24,20])
y=sm.vectorize(function)
print(y(a,b))


[10  4 30 40 10]
